### PR TITLE
LmcUser moved package name.

### PR DESCRIPTION
**Pull request by rarog**
LmcUser moved from Laminas-Commons to LM-Commons

### CODE REVIEW

**Comment by rarog** [comment]
The way I updated the packages, php 7.2 becomes incompatible. I could of course just try and to revert and just replace the lmc-user package instead of full update, but I let you decide.

**Comment by kokspflanze** [comment]
hi @rarog thanks for the update
could you create the composer.lock with php72? if you have problems with that no problem, i could do that too.

About the php72 incompatible, if you have time you can create a own PR to fix that problem, or write an issue=).
For me php72 is EOL, so if we switch to min php73 would be fine for me.

**Comment by rarog** [comment]
No problem, I just submitted a new pull request done with php 7.2, then you could do a final release with this php version and I'll prepare the switch to 7.3 in another pull request after this.

**Comment by kokspflanze** [comment]
i will add the testing for next week, hope thats okay for you=)
added on my list=)

**Pull request closed without merging**
