### PR TITLE
add support php 8.3

### PR DESCRIPTION
**Pull request by krumynin1993**

### CODE REVIEW

**Comment by kokspflanze** [comment]
hi @krumynin thanks for your PR, but looks like we have to wait for laminas-db
https://github.com/laminas/laminas-db/pull/293

hope, they add it soon.

**Comment by driehle** [comment]
`laminas-db` 2.19.0 with PHP 8.3 support has been released 🚀

**Comment by krumynin** [comment]
All tests success, can you merge it please?

**Comment by krumynin1993** [comment]
Can you make a new release? please

**Comment by kokspflanze** [comment]
@krumynin sure, i will create it later

**Comment by kokspflanze** [comment]
@krumynin done

**Pull request merged**
